/** BPS SIG wilayah snapshot, period 2025_2.2025. Generated by scripts/refresh-indonesia-regions.mjs.
 * Source: https://sig.bps.go.id/rest-drop-down/getwilayah. Codes use BPS, not Kemendagri namespace.
 * Local snapshot shared between server validation and client; no third-party browser requests.
 */
export type Regency = { id: string; provinceId: string; city: string; province: string };
export const INDONESIA_REGENCIES: Regency[] = [
  {
    "id": "1101",
    "provinceId": "11",
    "city": "KABUPATEN SIMEULUE",
    "province": "ACEH"
  },
  {
    "id": "1102",
    "provinceId": "11",
    "city": "KABUPATEN ACEH SINGKIL",
    "province": "ACEH"
  },
  {
    "id": "1103",
    "provinceId": "11",
    "city": "KABUPATEN ACEH SELATAN",
    "province": "ACEH"
  },
  {
    "id": "1104",
    "provinceId": "11",
    "city": "KABUPATEN ACEH TENGGARA",
    "province": "ACEH"
  },
  {
    "id": "1105",
    "provinceId": "11",
    "city": "KABUPATEN ACEH TIMUR",
    "province": "ACEH"
  },
  {
    "id": "1106",
    "provinceId": "11",
    "city": "KABUPATEN ACEH TENGAH",
    "province": "ACEH"
  },
  {
    "id": "1107",
    "provinceId": "11",
    "city": "KABUPATEN ACEH BARAT",
    "province": "ACEH"
  },
  {
    "id": "1108",
    "provinceId": "11",
    "city": "KABUPATEN ACEH BESAR",
    "province": "ACEH"
  },
  {
    "id": "1109",
    "provinceId": "11",
    "city": "KABUPATEN PIDIE",
    "province": "ACEH"
  },
  {
    "id": "1110",
    "provinceId": "11",
    "city": "KABUPATEN BIREUEN",
    "province": "ACEH"
  },
  {
    "id": "1111",
    "provinceId": "11",
    "city": "KABUPATEN ACEH UTARA",
    "province": "ACEH"
  },
  {
    "id": "1112",
    "provinceId": "11",
    "city": "KABUPATEN ACEH BARAT DAYA",
    "province": "ACEH"
  },
  {
    "id": "1113",
    "provinceId": "11",
    "city": "KABUPATEN GAYO LUES",
    "province": "ACEH"
  },
  {
    "id": "1114",
    "provinceId": "11",
    "city": "KABUPATEN ACEH TAMIANG",
    "province": "ACEH"
  },
  {
    "id": "1115",
    "provinceId": "11",
    "city": "KABUPATEN NAGAN RAYA",
    "province": "ACEH"
  },
  {
    "id": "1116",
    "provinceId": "11",
    "city": "KABUPATEN ACEH JAYA",
    "province": "ACEH"
  },
  {
    "id": "1117",
    "provinceId": "11",
    "city": "KABUPATEN BENER MERIAH",
    "province": "ACEH"
  },
  {
    "id": "1118",
    "provinceId": "11",
    "city": "KABUPATEN PIDIE JAYA",
    "province": "ACEH"
  },
  {
    "id": "1171",
    "provinceId": "11",
    "city": "KOTA BANDA ACEH",
    "province": "ACEH"
  },
  {
    "id": "1172",
    "provinceId": "11",
    "city": "KOTA SABANG",
    "province": "ACEH"
  },
  {
    "id": "1173",
    "provinceId": "11",
    "city": "KOTA LANGSA",
    "province": "ACEH"
  },
  {
    "id": "1174",
    "provinceId": "11",
    "city": "KOTA LHOKSEUMAWE",
    "province": "ACEH"
  },
  {
    "id": "1175",
    "provinceId": "11",
    "city": "KOTA SUBULUSSALAM",
    "province": "ACEH"
  },
  {
    "id": "1201",
    "provinceId": "12",
    "city": "KABUPATEN NIAS",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1202",
    "provinceId": "12",
    "city": "KABUPATEN MANDAILING NATAL",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1203",
    "provinceId": "12",
    "city": "KABUPATEN TAPANULI SELATAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1204",
    "provinceId": "12",
    "city": "KABUPATEN TAPANULI TENGAH",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1205",
    "provinceId": "12",
    "city": "KABUPATEN TAPANULI UTARA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1206",
    "provinceId": "12",
    "city": "KABUPATEN TOBA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1207",
    "provinceId": "12",
    "city": "KABUPATEN LABUHANBATU",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1208",
    "provinceId": "12",
    "city": "KABUPATEN ASAHAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1209",
    "provinceId": "12",
    "city": "KABUPATEN SIMALUNGUN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1210",
    "provinceId": "12",
    "city": "KABUPATEN DAIRI",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1211",
    "provinceId": "12",
    "city": "KABUPATEN KARO",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1212",
    "provinceId": "12",
    "city": "KABUPATEN DELI SERDANG",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1213",
    "provinceId": "12",
    "city": "KABUPATEN LANGKAT",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1214",
    "provinceId": "12",
    "city": "KABUPATEN NIAS SELATAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1215",
    "provinceId": "12",
    "city": "KABUPATEN HUMBANG HASUNDUTAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1216",
    "provinceId": "12",
    "city": "KABUPATEN PAKPAK BHARAT",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1217",
    "provinceId": "12",
    "city": "KABUPATEN SAMOSIR",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1218",
    "provinceId": "12",
    "city": "KABUPATEN SERDANG BEDAGAI",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1219",
    "provinceId": "12",
    "city": "KABUPATEN BATU BARA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1220",
    "provinceId": "12",
    "city": "KABUPATEN PADANG LAWAS UTARA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1221",
    "provinceId": "12",
    "city": "KABUPATEN PADANG LAWAS",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1222",
    "provinceId": "12",
    "city": "KABUPATEN LABUHANBATU SELATAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1223",
    "provinceId": "12",
    "city": "KABUPATEN LABUHANBATU UTARA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1224",
    "provinceId": "12",
    "city": "KABUPATEN NIAS UTARA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1225",
    "provinceId": "12",
    "city": "KABUPATEN NIAS BARAT",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1271",
    "provinceId": "12",
    "city": "KOTA SIBOLGA",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1272",
    "provinceId": "12",
    "city": "KOTA TANJUNGBALAI",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1273",
    "provinceId": "12",
    "city": "KOTA PEMATANGSIANTAR",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1274",
    "provinceId": "12",
    "city": "KOTA TEBING TINGGI",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1275",
    "provinceId": "12",
    "city": "KOTA MEDAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1276",
    "provinceId": "12",
    "city": "KOTA BINJAI",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1277",
    "provinceId": "12",
    "city": "KOTA PADANGSIDIMPUAN",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1278",
    "provinceId": "12",
    "city": "KOTA GUNUNGSITOLI",
    "province": "SUMATERA UTARA"
  },
  {
    "id": "1301",
    "provinceId": "13",
    "city": "KABUPATEN KEPULAUAN MENTAWAI",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1302",
    "provinceId": "13",
    "city": "KABUPATEN PESISIR SELATAN",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1303",
    "provinceId": "13",
    "city": "KABUPATEN SOLOK",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1304",
    "provinceId": "13",
    "city": "KABUPATEN SIJUNJUNG",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1305",
    "provinceId": "13",
    "city": "KABUPATEN TANAH DATAR",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1306",
    "provinceId": "13",
    "city": "KABUPATEN PADANG PARIAMAN",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1307",
    "provinceId": "13",
    "city": "KABUPATEN AGAM",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1308",
    "provinceId": "13",
    "city": "KABUPATEN LIMA PULUH KOTA",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1309",
    "provinceId": "13",
    "city": "KABUPATEN PASAMAN",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1310",
    "provinceId": "13",
    "city": "KABUPATEN SOLOK SELATAN",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1311",
    "provinceId": "13",
    "city": "KABUPATEN DHARMASRAYA",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1312",
    "provinceId": "13",
    "city": "KABUPATEN PASAMAN BARAT",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1371",
    "provinceId": "13",
    "city": "KOTA PADANG",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1372",
    "provinceId": "13",
    "city": "KOTA SOLOK",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1373",
    "provinceId": "13",
    "city": "KOTA SAWAHLUNTO",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1374",
    "provinceId": "13",
    "city": "KOTA PADANG PANJANG",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1375",
    "provinceId": "13",
    "city": "KOTA BUKITTINGGI",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1376",
    "provinceId": "13",
    "city": "KOTA PAYAKUMBUH",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1377",
    "provinceId": "13",
    "city": "KOTA PARIAMAN",
    "province": "SUMATERA BARAT"
  },
  {
    "id": "1401",
    "provinceId": "14",
    "city": "KABUPATEN KUANTAN SINGINGI",
    "province": "RIAU"
  },
  {
    "id": "1402",
    "provinceId": "14",
    "city": "KABUPATEN INDRAGIRI HULU",
    "province": "RIAU"
  },
  {
    "id": "1403",
    "provinceId": "14",
    "city": "KABUPATEN INDRAGIRI HILIR",
    "province": "RIAU"
  },
  {
    "id": "1404",
    "provinceId": "14",
    "city": "KABUPATEN PELALAWAN",
    "province": "RIAU"
  },
  {
    "id": "1405",
    "provinceId": "14",
    "city": "KABUPATEN SIAK",
    "province": "RIAU"
  },
  {
    "id": "1406",
    "provinceId": "14",
    "city": "KABUPATEN KAMPAR",
    "province": "RIAU"
  },
  {
    "id": "1407",
    "provinceId": "14",
    "city": "KABUPATEN ROKAN HULU",
    "province": "RIAU"
  },
  {
    "id": "1408",
    "provinceId": "14",
    "city": "KABUPATEN BENGKALIS",
    "province": "RIAU"
  },
  {
    "id": "1409",
    "provinceId": "14",
    "city": "KABUPATEN ROKAN HILIR",
    "province": "RIAU"
  },
  {
    "id": "1410",
    "provinceId": "14",
    "city": "KABUPATEN KEPULAUAN MERANTI",
    "province": "RIAU"
  },
  {
    "id": "1471",
    "provinceId": "14",
    "city": "KOTA PEKANBARU",
    "province": "RIAU"
  },
  {
    "id": "1473",
    "provinceId": "14",
    "city": "KOTA DUMAI",
    "province": "RIAU"
  },
  {
    "id": "1501",
    "provinceId": "15",
    "city": "KABUPATEN KERINCI",
    "province": "JAMBI"
  },
  {
    "id": "1502",
    "provinceId": "15",
    "city": "KABUPATEN MERANGIN",
    "province": "JAMBI"
  },
  {
    "id": "1503",
    "provinceId": "15",
    "city": "KABUPATEN SAROLANGUN",
    "province": "JAMBI"
  },
  {
    "id": "1504",
    "provinceId": "15",
    "city": "KABUPATEN BATANG HARI",
    "province": "JAMBI"
  },
  {
    "id": "1505",
    "provinceId": "15",
    "city": "KABUPATEN MUARO JAMBI",
    "province": "JAMBI"
  },
  {
    "id": "1506",
    "provinceId": "15",
    "city": "KABUPATEN TANJUNG JABUNG TIMUR",
    "province": "JAMBI"
  },
  {
    "id": "1507",
    "provinceId": "15",
    "city": "KABUPATEN TANJUNG JABUNG BARAT",
    "province": "JAMBI"
  },
  {
    "id": "1508",
    "provinceId": "15",
    "city": "KABUPATEN TEBO",
    "province": "JAMBI"
  },
  {
    "id": "1509",
    "provinceId": "15",
    "city": "KABUPATEN BUNGO",
    "province": "JAMBI"
  },
  {
    "id": "1571",
    "provinceId": "15",
    "city": "KOTA JAMBI",
    "province": "JAMBI"
  },
  {
    "id": "1572",
    "provinceId": "15",
    "city": "KOTA SUNGAI PENUH",
    "province": "JAMBI"
  },
  {
    "id": "1601",
    "provinceId": "16",
    "city": "KABUPATEN OGAN KOMERING ULU",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1602",
    "provinceId": "16",
    "city": "KABUPATEN OGAN KOMERING ILIR",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1603",
    "provinceId": "16",
    "city": "KABUPATEN MUARA ENIM",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1604",
    "provinceId": "16",
    "city": "KABUPATEN LAHAT",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1605",
    "provinceId": "16",
    "city": "KABUPATEN MUSI RAWAS",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1606",
    "provinceId": "16",
    "city": "KABUPATEN MUSI BANYUASIN",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1607",
    "provinceId": "16",
    "city": "KABUPATEN BANYUASIN",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1608",
    "provinceId": "16",
    "city": "KABUPATEN OGAN KOMERING ULU SELATAN",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1609",
    "provinceId": "16",
    "city": "KABUPATEN OGAN KOMERING ULU TIMUR",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1610",
    "provinceId": "16",
    "city": "KABUPATEN OGAN ILIR",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1611",
    "provinceId": "16",
    "city": "KABUPATEN EMPAT LAWANG",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1612",
    "provinceId": "16",
    "city": "KABUPATEN PENUKAL ABAB LEMATANG ILIR",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1613",
    "provinceId": "16",
    "city": "KABUPATEN MUSI RAWAS UTARA",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1671",
    "provinceId": "16",
    "city": "KOTA PALEMBANG",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1672",
    "provinceId": "16",
    "city": "KOTA PRABUMULIH",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1673",
    "provinceId": "16",
    "city": "KOTA PAGAR ALAM",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1674",
    "provinceId": "16",
    "city": "KOTA LUBUKLINGGAU",
    "province": "SUMATERA SELATAN"
  },
  {
    "id": "1701",
    "provinceId": "17",
    "city": "KABUPATEN BENGKULU SELATAN",
    "province": "BENGKULU"
  },
  {
    "id": "1702",
    "provinceId": "17",
    "city": "KABUPATEN REJANG LEBONG",
    "province": "BENGKULU"
  },
  {
    "id": "1703",
    "provinceId": "17",
    "city": "KABUPATEN BENGKULU UTARA",
    "province": "BENGKULU"
  },
  {
    "id": "1704",
    "provinceId": "17",
    "city": "KABUPATEN KAUR",
    "province": "BENGKULU"
  },
  {
    "id": "1705",
    "provinceId": "17",
    "city": "KABUPATEN SELUMA",
    "province": "BENGKULU"
  },
  {
    "id": "1706",
    "provinceId": "17",
    "city": "KABUPATEN MUKOMUKO",
    "province": "BENGKULU"
  },
  {
    "id": "1707",
    "provinceId": "17",
    "city": "KABUPATEN LEBONG",
    "province": "BENGKULU"
  },
  {
    "id": "1708",
    "provinceId": "17",
    "city": "KABUPATEN KEPAHIANG",
    "province": "BENGKULU"
  },
  {
    "id": "1709",
    "provinceId": "17",
    "city": "KABUPATEN BENGKULU TENGAH",
    "province": "BENGKULU"
  },
  {
    "id": "1771",
    "provinceId": "17",
    "city": "KOTA BENGKULU",
    "province": "BENGKULU"
  },
  {
    "id": "1801",
    "provinceId": "18",
    "city": "KABUPATEN LAMPUNG BARAT",
    "province": "LAMPUNG"
  },
  {
    "id": "1802",
    "provinceId": "18",
    "city": "KABUPATEN TANGGAMUS",
    "province": "LAMPUNG"
  },
  {
    "id": "1803",
    "provinceId": "18",
    "city": "KABUPATEN LAMPUNG SELATAN",
    "province": "LAMPUNG"
  },
  {
    "id": "1804",
    "provinceId": "18",
    "city": "KABUPATEN LAMPUNG TIMUR",
    "province": "LAMPUNG"
  },
  {
    "id": "1805",
    "provinceId": "18",
    "city": "KABUPATEN LAMPUNG TENGAH",
    "province": "LAMPUNG"
  },
  {
    "id": "1806",
    "provinceId": "18",
    "city": "KABUPATEN LAMPUNG UTARA",
    "province": "LAMPUNG"
  },
  {
    "id": "1807",
    "provinceId": "18",
    "city": "KABUPATEN WAY KANAN",
    "province": "LAMPUNG"
  },
  {
    "id": "1808",
    "provinceId": "18",
    "city": "KABUPATEN TULANG BAWANG",
    "province": "LAMPUNG"
  },
  {
    "id": "1809",
    "provinceId": "18",
    "city": "KABUPATEN PESAWARAN",
    "province": "LAMPUNG"
  },
  {
    "id": "1810",
    "provinceId": "18",
    "city": "KABUPATEN PRINGSEWU",
    "province": "LAMPUNG"
  },
  {
    "id": "1811",
    "provinceId": "18",
    "city": "KABUPATEN MESUJI",
    "province": "LAMPUNG"
  },
  {
    "id": "1812",
    "provinceId": "18",
    "city": "KABUPATEN TULANG BAWANG BARAT",
    "province": "LAMPUNG"
  },
  {
    "id": "1813",
    "provinceId": "18",
    "city": "KABUPATEN PESISIR BARAT",
    "province": "LAMPUNG"
  },
  {
    "id": "1871",
    "provinceId": "18",
    "city": "KOTA BANDAR LAMPUNG",
    "province": "LAMPUNG"
  },
  {
    "id": "1872",
    "provinceId": "18",
    "city": "KOTA METRO",
    "province": "LAMPUNG"
  },
  {
    "id": "1901",
    "provinceId": "19",
    "city": "KABUPATEN BANGKA",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "1902",
    "provinceId": "19",
    "city": "KABUPATEN BELITUNG",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "1903",
    "provinceId": "19",
    "city": "KABUPATEN BANGKA BARAT",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "1904",
    "provinceId": "19",
    "city": "KABUPATEN BANGKA TENGAH",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "1905",
    "provinceId": "19",
    "city": "KABUPATEN BANGKA SELATAN",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "1906",
    "provinceId": "19",
    "city": "KABUPATEN BELITUNG TIMUR",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "1971",
    "provinceId": "19",
    "city": "KOTA PANGKAL PINANG",
    "province": "KEPULAUAN BANGKA BELITUNG"
  },
  {
    "id": "2101",
    "provinceId": "21",
    "city": "KABUPATEN KARIMUN",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "2102",
    "provinceId": "21",
    "city": "KABUPATEN BINTAN",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "2103",
    "provinceId": "21",
    "city": "KABUPATEN NATUNA",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "2104",
    "provinceId": "21",
    "city": "KABUPATEN LINGGA",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "2105",
    "provinceId": "21",
    "city": "KABUPATEN KEPULAUAN ANAMBAS",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "2171",
    "provinceId": "21",
    "city": "KOTA BATAM",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "2172",
    "provinceId": "21",
    "city": "KOTA TANJUNG PINANG",
    "province": "KEPULAUAN RIAU"
  },
  {
    "id": "3101",
    "provinceId": "31",
    "city": "KABUPATEN KEPULAUAN SERIBU",
    "province": "DKI JAKARTA"
  },
  {
    "id": "3171",
    "provinceId": "31",
    "city": "KOTA JAKARTA SELATAN",
    "province": "DKI JAKARTA"
  },
  {
    "id": "3172",
    "provinceId": "31",
    "city": "KOTA JAKARTA TIMUR",
    "province": "DKI JAKARTA"
  },
  {
    "id": "3173",
    "provinceId": "31",
    "city": "KOTA JAKARTA PUSAT",
    "province": "DKI JAKARTA"
  },
  {
    "id": "3174",
    "provinceId": "31",
    "city": "KOTA JAKARTA BARAT",
    "province": "DKI JAKARTA"
  },
  {
    "id": "3175",
    "provinceId": "31",
    "city": "KOTA JAKARTA UTARA",
    "province": "DKI JAKARTA"
  },
  {
    "id": "3201",
    "provinceId": "32",
    "city": "KABUPATEN BOGOR",
    "province": "JAWA BARAT"
  },
  {
    "id": "3202",
    "provinceId": "32",
    "city": "KABUPATEN SUKABUMI",
    "province": "JAWA BARAT"
  },
  {
    "id": "3203",
    "provinceId": "32",
    "city": "KABUPATEN CIANJUR",
    "province": "JAWA BARAT"
  },
  {
    "id": "3204",
    "provinceId": "32",
    "city": "KABUPATEN BANDUNG",
    "province": "JAWA BARAT"
  },
  {
    "id": "3205",
    "provinceId": "32",
    "city": "KABUPATEN GARUT",
    "province": "JAWA BARAT"
  },
  {
    "id": "3206",
    "provinceId": "32",
    "city": "KABUPATEN TASIKMALAYA",
    "province": "JAWA BARAT"
  },
  {
    "id": "3207",
    "provinceId": "32",
    "city": "KABUPATEN CIAMIS",
    "province": "JAWA BARAT"
  },
  {
    "id": "3208",
    "provinceId": "32",
    "city": "KABUPATEN KUNINGAN",
    "province": "JAWA BARAT"
  },
  {
    "id": "3209",
    "provinceId": "32",
    "city": "KABUPATEN CIREBON",
    "province": "JAWA BARAT"
  },
  {
    "id": "3210",
    "provinceId": "32",
    "city": "KABUPATEN MAJALENGKA",
    "province": "JAWA BARAT"
  },
  {
    "id": "3211",
    "provinceId": "32",
    "city": "KABUPATEN SUMEDANG",
    "province": "JAWA BARAT"
  },
  {
    "id": "3212",
    "provinceId": "32",
    "city": "KABUPATEN INDRAMAYU",
    "province": "JAWA BARAT"
  },
  {
    "id": "3213",
    "provinceId": "32",
    "city": "KABUPATEN SUBANG",
    "province": "JAWA BARAT"
  },
  {
    "id": "3214",
    "provinceId": "32",
    "city": "KABUPATEN PURWAKARTA",
    "province": "JAWA BARAT"
  },
  {
    "id": "3215",
    "provinceId": "32",
    "city": "KABUPATEN KARAWANG",
    "province": "JAWA BARAT"
  },
  {
    "id": "3216",
    "provinceId": "32",
    "city": "KABUPATEN BEKASI",
    "province": "JAWA BARAT"
  },
  {
    "id": "3217",
    "provinceId": "32",
    "city": "KABUPATEN BANDUNG BARAT",
    "province": "JAWA BARAT"
  },
  {
    "id": "3218",
    "provinceId": "32",
    "city": "KABUPATEN PANGANDARAN",
    "province": "JAWA BARAT"
  },
  {
    "id": "3271",
    "provinceId": "32",
    "city": "KOTA BOGOR",
    "province": "JAWA BARAT"
  },
  {
    "id": "3272",
    "provinceId": "32",
    "city": "KOTA SUKABUMI",
    "province": "JAWA BARAT"
  },
  {
    "id": "3273",
    "provinceId": "32",
    "city": "KOTA BANDUNG",
    "province": "JAWA BARAT"
  },
  {
    "id": "3274",
    "provinceId": "32",
    "city": "KOTA CIREBON",
    "province": "JAWA BARAT"
  },
  {
    "id": "3275",
    "provinceId": "32",
    "city": "KOTA BEKASI",
    "province": "JAWA BARAT"
  },
  {
    "id": "3276",
    "provinceId": "32",
    "city": "KOTA DEPOK",
    "province": "JAWA BARAT"
  },
  {
    "id": "3277",
    "provinceId": "32",
    "city": "KOTA CIMAHI",
    "province": "JAWA BARAT"
  },
  {
    "id": "3278",
    "provinceId": "32",
    "city": "KOTA TASIKMALAYA",
    "province": "JAWA BARAT"
  },
  {
    "id": "3279",
    "provinceId": "32",
    "city": "KOTA BANJAR",
    "province": "JAWA BARAT"
  },
  {
    "id": "3301",
    "provinceId": "33",
    "city": "KABUPATEN CILACAP",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3302",
    "provinceId": "33",
    "city": "KABUPATEN BANYUMAS",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3303",
    "provinceId": "33",
    "city": "KABUPATEN PURBALINGGA",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3304",
    "provinceId": "33",
    "city": "KABUPATEN BANJARNEGARA",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3305",
    "provinceId": "33",
    "city": "KABUPATEN KEBUMEN",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3306",
    "provinceId": "33",
    "city": "KABUPATEN PURWOREJO",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3307",
    "provinceId": "33",
    "city": "KABUPATEN WONOSOBO",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3308",
    "provinceId": "33",
    "city": "KABUPATEN MAGELANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3309",
    "provinceId": "33",
    "city": "KABUPATEN BOYOLALI",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3310",
    "provinceId": "33",
    "city": "KABUPATEN KLATEN",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3311",
    "provinceId": "33",
    "city": "KABUPATEN SUKOHARJO",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3312",
    "provinceId": "33",
    "city": "KABUPATEN WONOGIRI",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3313",
    "provinceId": "33",
    "city": "KABUPATEN KARANGANYAR",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3314",
    "provinceId": "33",
    "city": "KABUPATEN SRAGEN",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3315",
    "provinceId": "33",
    "city": "KABUPATEN GROBOGAN",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3316",
    "provinceId": "33",
    "city": "KABUPATEN BLORA",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3317",
    "provinceId": "33",
    "city": "KABUPATEN REMBANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3318",
    "provinceId": "33",
    "city": "KABUPATEN PATI",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3319",
    "provinceId": "33",
    "city": "KABUPATEN KUDUS",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3320",
    "provinceId": "33",
    "city": "KABUPATEN JEPARA",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3321",
    "provinceId": "33",
    "city": "KABUPATEN DEMAK",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3322",
    "provinceId": "33",
    "city": "KABUPATEN SEMARANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3323",
    "provinceId": "33",
    "city": "KABUPATEN TEMANGGUNG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3324",
    "provinceId": "33",
    "city": "KABUPATEN KENDAL",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3325",
    "provinceId": "33",
    "city": "KABUPATEN BATANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3326",
    "provinceId": "33",
    "city": "KABUPATEN PEKALONGAN",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3327",
    "provinceId": "33",
    "city": "KABUPATEN PEMALANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3328",
    "provinceId": "33",
    "city": "KABUPATEN TEGAL",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3329",
    "provinceId": "33",
    "city": "KABUPATEN BREBES",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3371",
    "provinceId": "33",
    "city": "KOTA MAGELANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3372",
    "provinceId": "33",
    "city": "KOTA SURAKARTA",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3373",
    "provinceId": "33",
    "city": "KOTA SALATIGA",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3374",
    "provinceId": "33",
    "city": "KOTA SEMARANG",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3375",
    "provinceId": "33",
    "city": "KOTA PEKALONGAN",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3376",
    "provinceId": "33",
    "city": "KOTA TEGAL",
    "province": "JAWA TENGAH"
  },
  {
    "id": "3401",
    "provinceId": "34",
    "city": "KABUPATEN KULON PROGO",
    "province": "DI YOGYAKARTA"
  },
  {
    "id": "3402",
    "provinceId": "34",
    "city": "KABUPATEN BANTUL",
    "province": "DI YOGYAKARTA"
  },
  {
    "id": "3403",
    "provinceId": "34",
    "city": "KABUPATEN GUNUNGKIDUL",
    "province": "DI YOGYAKARTA"
  },
  {
    "id": "3404",
    "provinceId": "34",
    "city": "KABUPATEN SLEMAN",
    "province": "DI YOGYAKARTA"
  },
  {
    "id": "3471",
    "provinceId": "34",
    "city": "KOTA YOGYAKARTA",
    "province": "DI YOGYAKARTA"
  },
  {
    "id": "3501",
    "provinceId": "35",
    "city": "KABUPATEN PACITAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3502",
    "provinceId": "35",
    "city": "KABUPATEN PONOROGO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3503",
    "provinceId": "35",
    "city": "KABUPATEN TRENGGALEK",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3504",
    "provinceId": "35",
    "city": "KABUPATEN TULUNGAGUNG",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3505",
    "provinceId": "35",
    "city": "KABUPATEN BLITAR",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3506",
    "provinceId": "35",
    "city": "KABUPATEN KEDIRI",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3507",
    "provinceId": "35",
    "city": "KABUPATEN MALANG",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3508",
    "provinceId": "35",
    "city": "KABUPATEN LUMAJANG",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3509",
    "provinceId": "35",
    "city": "KABUPATEN JEMBER",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3510",
    "provinceId": "35",
    "city": "KABUPATEN BANYUWANGI",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3511",
    "provinceId": "35",
    "city": "KABUPATEN BONDOWOSO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3512",
    "provinceId": "35",
    "city": "KABUPATEN SITUBONDO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3513",
    "provinceId": "35",
    "city": "KABUPATEN PROBOLINGGO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3514",
    "provinceId": "35",
    "city": "KABUPATEN PASURUAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3515",
    "provinceId": "35",
    "city": "KABUPATEN SIDOARJO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3516",
    "provinceId": "35",
    "city": "KABUPATEN MOJOKERTO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3517",
    "provinceId": "35",
    "city": "KABUPATEN JOMBANG",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3518",
    "provinceId": "35",
    "city": "KABUPATEN NGANJUK",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3519",
    "provinceId": "35",
    "city": "KABUPATEN MADIUN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3520",
    "provinceId": "35",
    "city": "KABUPATEN MAGETAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3521",
    "provinceId": "35",
    "city": "KABUPATEN NGAWI",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3522",
    "provinceId": "35",
    "city": "KABUPATEN BOJONEGORO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3523",
    "provinceId": "35",
    "city": "KABUPATEN TUBAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3524",
    "provinceId": "35",
    "city": "KABUPATEN LAMONGAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3525",
    "provinceId": "35",
    "city": "KABUPATEN GRESIK",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3526",
    "provinceId": "35",
    "city": "KABUPATEN BANGKALAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3527",
    "provinceId": "35",
    "city": "KABUPATEN SAMPANG",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3528",
    "provinceId": "35",
    "city": "KABUPATEN PAMEKASAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3529",
    "provinceId": "35",
    "city": "KABUPATEN SUMENEP",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3571",
    "provinceId": "35",
    "city": "KOTA KEDIRI",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3572",
    "provinceId": "35",
    "city": "KOTA BLITAR",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3573",
    "provinceId": "35",
    "city": "KOTA MALANG",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3574",
    "provinceId": "35",
    "city": "KOTA PROBOLINGGO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3575",
    "provinceId": "35",
    "city": "KOTA PASURUAN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3576",
    "provinceId": "35",
    "city": "KOTA MOJOKERTO",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3577",
    "provinceId": "35",
    "city": "KOTA MADIUN",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3578",
    "provinceId": "35",
    "city": "KOTA SURABAYA",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3579",
    "provinceId": "35",
    "city": "KOTA BATU",
    "province": "JAWA TIMUR"
  },
  {
    "id": "3601",
    "provinceId": "36",
    "city": "KABUPATEN PANDEGLANG",
    "province": "BANTEN"
  },
  {
    "id": "3602",
    "provinceId": "36",
    "city": "KABUPATEN LEBAK",
    "province": "BANTEN"
  },
  {
    "id": "3603",
    "provinceId": "36",
    "city": "KABUPATEN TANGERANG",
    "province": "BANTEN"
  },
  {
    "id": "3604",
    "provinceId": "36",
    "city": "KABUPATEN SERANG",
    "province": "BANTEN"
  },
  {
    "id": "3671",
    "provinceId": "36",
    "city": "KOTA TANGERANG",
    "province": "BANTEN"
  },
  {
    "id": "3672",
    "provinceId": "36",
    "city": "KOTA CILEGON",
    "province": "BANTEN"
  },
  {
    "id": "3673",
    "provinceId": "36",
    "city": "KOTA SERANG",
    "province": "BANTEN"
  },
  {
    "id": "3674",
    "provinceId": "36",
    "city": "KOTA TANGERANG SELATAN",
    "province": "BANTEN"
  },
  {
    "id": "5101",
    "provinceId": "51",
    "city": "KABUPATEN JEMBRANA",
    "province": "BALI"
  },
  {
    "id": "5102",
    "provinceId": "51",
    "city": "KABUPATEN TABANAN",
    "province": "BALI"
  },
  {
    "id": "5103",
    "provinceId": "51",
    "city": "KABUPATEN BADUNG",
    "province": "BALI"
  },
  {
    "id": "5104",
    "provinceId": "51",
    "city": "KABUPATEN GIANYAR",
    "province": "BALI"
  },
  {
    "id": "5105",
    "provinceId": "51",
    "city": "KABUPATEN KLUNGKUNG",
    "province": "BALI"
  },
  {
    "id": "5106",
    "provinceId": "51",
    "city": "KABUPATEN BANGLI",
    "province": "BALI"
  },
  {
    "id": "5107",
    "provinceId": "51",
    "city": "KABUPATEN KARANGASEM",
    "province": "BALI"
  },
  {
    "id": "5108",
    "provinceId": "51",
    "city": "KABUPATEN BULELENG",
    "province": "BALI"
  },
  {
    "id": "5171",
    "provinceId": "51",
    "city": "KOTA DENPASAR",
    "province": "BALI"
  },
  {
    "id": "5201",
    "provinceId": "52",
    "city": "KABUPATEN LOMBOK BARAT",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5202",
    "provinceId": "52",
    "city": "KABUPATEN LOMBOK TENGAH",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5203",
    "provinceId": "52",
    "city": "KABUPATEN LOMBOK TIMUR",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5204",
    "provinceId": "52",
    "city": "KABUPATEN SUMBAWA",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5205",
    "provinceId": "52",
    "city": "KABUPATEN DOMPU",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5206",
    "provinceId": "52",
    "city": "KABUPATEN BIMA",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5207",
    "provinceId": "52",
    "city": "KABUPATEN SUMBAWA BARAT",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5208",
    "provinceId": "52",
    "city": "KABUPATEN LOMBOK UTARA",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5271",
    "provinceId": "52",
    "city": "KOTA MATARAM",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5272",
    "provinceId": "52",
    "city": "KOTA BIMA",
    "province": "NUSA TENGGARA BARAT"
  },
  {
    "id": "5301",
    "provinceId": "53",
    "city": "KABUPATEN SUMBA BARAT",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5302",
    "provinceId": "53",
    "city": "KABUPATEN SUMBA TIMUR",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5303",
    "provinceId": "53",
    "city": "KABUPATEN KUPANG",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5304",
    "provinceId": "53",
    "city": "KABUPATEN TIMOR TENGAH SELATAN",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5305",
    "provinceId": "53",
    "city": "KABUPATEN TIMOR TENGAH UTARA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5306",
    "provinceId": "53",
    "city": "KABUPATEN BELU",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5307",
    "provinceId": "53",
    "city": "KABUPATEN ALOR",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5308",
    "provinceId": "53",
    "city": "KABUPATEN LEMBATA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5309",
    "provinceId": "53",
    "city": "KABUPATEN FLORES TIMUR",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5310",
    "provinceId": "53",
    "city": "KABUPATEN SIKKA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5311",
    "provinceId": "53",
    "city": "KABUPATEN ENDE",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5312",
    "provinceId": "53",
    "city": "KABUPATEN NGADA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5313",
    "provinceId": "53",
    "city": "KABUPATEN MANGGARAI",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5314",
    "provinceId": "53",
    "city": "KABUPATEN ROTE NDAO",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5315",
    "provinceId": "53",
    "city": "KABUPATEN MANGGARAI BARAT",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5316",
    "provinceId": "53",
    "city": "KABUPATEN SUMBA TENGAH",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5317",
    "provinceId": "53",
    "city": "KABUPATEN SUMBA BARAT DAYA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5318",
    "provinceId": "53",
    "city": "KABUPATEN NAGEKEO",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5319",
    "provinceId": "53",
    "city": "KABUPATEN MANGGARAI TIMUR",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5320",
    "provinceId": "53",
    "city": "KABUPATEN SABU RAIJUA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5321",
    "provinceId": "53",
    "city": "KABUPATEN MALAKA",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "5371",
    "provinceId": "53",
    "city": "KOTA KUPANG",
    "province": "NUSA TENGGARA TIMUR"
  },
  {
    "id": "6101",
    "provinceId": "61",
    "city": "KABUPATEN SAMBAS",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6102",
    "provinceId": "61",
    "city": "KABUPATEN BENGKAYANG",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6103",
    "provinceId": "61",
    "city": "KABUPATEN LANDAK",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6104",
    "provinceId": "61",
    "city": "KABUPATEN MEMPAWAH",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6105",
    "provinceId": "61",
    "city": "KABUPATEN SANGGAU",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6106",
    "provinceId": "61",
    "city": "KABUPATEN KETAPANG",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6107",
    "provinceId": "61",
    "city": "KABUPATEN SINTANG",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6108",
    "provinceId": "61",
    "city": "KABUPATEN KAPUAS HULU",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6109",
    "provinceId": "61",
    "city": "KABUPATEN SEKADAU",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6110",
    "provinceId": "61",
    "city": "KABUPATEN MELAWI",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6111",
    "provinceId": "61",
    "city": "KABUPATEN KAYONG UTARA",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6112",
    "provinceId": "61",
    "city": "KABUPATEN KUBU RAYA",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6171",
    "provinceId": "61",
    "city": "KOTA PONTIANAK",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6172",
    "provinceId": "61",
    "city": "KOTA SINGKAWANG",
    "province": "KALIMANTAN BARAT"
  },
  {
    "id": "6201",
    "provinceId": "62",
    "city": "KABUPATEN KOTAWARINGIN BARAT",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6202",
    "provinceId": "62",
    "city": "KABUPATEN KOTAWARINGIN TIMUR",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6203",
    "provinceId": "62",
    "city": "KABUPATEN KAPUAS",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6204",
    "provinceId": "62",
    "city": "KABUPATEN BARITO SELATAN",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6205",
    "provinceId": "62",
    "city": "KABUPATEN BARITO UTARA",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6206",
    "provinceId": "62",
    "city": "KABUPATEN SUKAMARA",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6207",
    "provinceId": "62",
    "city": "KABUPATEN LAMANDAU",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6208",
    "provinceId": "62",
    "city": "KABUPATEN SERUYAN",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6209",
    "provinceId": "62",
    "city": "KABUPATEN KATINGAN",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6210",
    "provinceId": "62",
    "city": "KABUPATEN PULANG PISAU",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6211",
    "provinceId": "62",
    "city": "KABUPATEN GUNUNG MAS",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6212",
    "provinceId": "62",
    "city": "KABUPATEN BARITO TIMUR",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6213",
    "provinceId": "62",
    "city": "KABUPATEN MURUNG RAYA",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6271",
    "provinceId": "62",
    "city": "KOTA PALANGKA RAYA",
    "province": "KALIMANTAN TENGAH"
  },
  {
    "id": "6301",
    "provinceId": "63",
    "city": "KABUPATEN TANAH LAUT",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6302",
    "provinceId": "63",
    "city": "KABUPATEN KOTABARU",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6303",
    "provinceId": "63",
    "city": "KABUPATEN BANJAR",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6304",
    "provinceId": "63",
    "city": "KABUPATEN BARITO KUALA",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6305",
    "provinceId": "63",
    "city": "KABUPATEN TAPIN",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6306",
    "provinceId": "63",
    "city": "KABUPATEN HULU SUNGAI SELATAN",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6307",
    "provinceId": "63",
    "city": "KABUPATEN HULU SUNGAI TENGAH",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6308",
    "provinceId": "63",
    "city": "KABUPATEN HULU SUNGAI UTARA",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6309",
    "provinceId": "63",
    "city": "KABUPATEN TABALONG",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6310",
    "provinceId": "63",
    "city": "KABUPATEN TANAH BUMBU",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6311",
    "provinceId": "63",
    "city": "KABUPATEN BALANGAN",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6371",
    "provinceId": "63",
    "city": "KOTA BANJARMASIN",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6372",
    "provinceId": "63",
    "city": "KOTA BANJARBARU",
    "province": "KALIMANTAN SELATAN"
  },
  {
    "id": "6401",
    "provinceId": "64",
    "city": "KABUPATEN PASER",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6402",
    "provinceId": "64",
    "city": "KABUPATEN KUTAI BARAT",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6403",
    "provinceId": "64",
    "city": "KABUPATEN KUTAI KARTANEGARA",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6404",
    "provinceId": "64",
    "city": "KABUPATEN KUTAI TIMUR",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6405",
    "provinceId": "64",
    "city": "KABUPATEN BERAU",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6409",
    "provinceId": "64",
    "city": "KABUPATEN PENAJAM PASER UTARA",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6411",
    "provinceId": "64",
    "city": "KABUPATEN MAHAKAM ULU",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6471",
    "provinceId": "64",
    "city": "KOTA BALIKPAPAN",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6472",
    "provinceId": "64",
    "city": "KOTA SAMARINDA",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6474",
    "provinceId": "64",
    "city": "KOTA BONTANG",
    "province": "KALIMANTAN TIMUR"
  },
  {
    "id": "6501",
    "provinceId": "65",
    "city": "KABUPATEN MALINAU",
    "province": "KALIMANTAN UTARA"
  },
  {
    "id": "6502",
    "provinceId": "65",
    "city": "KABUPATEN BULUNGAN",
    "province": "KALIMANTAN UTARA"
  },
  {
    "id": "6503",
    "provinceId": "65",
    "city": "KABUPATEN TANA TIDUNG",
    "province": "KALIMANTAN UTARA"
  },
  {
    "id": "6504",
    "provinceId": "65",
    "city": "KABUPATEN NUNUKAN",
    "province": "KALIMANTAN UTARA"
  },
  {
    "id": "6571",
    "provinceId": "65",
    "city": "KOTA TARAKAN",
    "province": "KALIMANTAN UTARA"
  },
  {
    "id": "7101",
    "provinceId": "71",
    "city": "KABUPATEN BOLAANG MONGONDOW",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7102",
    "provinceId": "71",
    "city": "KABUPATEN MINAHASA",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7103",
    "provinceId": "71",
    "city": "KABUPATEN KEPULAUAN SANGIHE",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7104",
    "provinceId": "71",
    "city": "KABUPATEN KEPULAUAN TALAUD",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7105",
    "provinceId": "71",
    "city": "KABUPATEN MINAHASA SELATAN",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7106",
    "provinceId": "71",
    "city": "KABUPATEN MINAHASA UTARA",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7107",
    "provinceId": "71",
    "city": "KABUPATEN BOLAANG MONGONDOW UTARA",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7108",
    "provinceId": "71",
    "city": "KABUPATEN KEPULAUAN SIAU TAGULANDANG BIARO",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7109",
    "provinceId": "71",
    "city": "KABUPATEN MINAHASA TENGGARA",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7110",
    "provinceId": "71",
    "city": "KABUPATEN BOLAANG MONGONDOW SELATAN",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7111",
    "provinceId": "71",
    "city": "KABUPATEN BOLAANG MONGONDOW TIMUR",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7171",
    "provinceId": "71",
    "city": "KOTA MANADO",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7172",
    "provinceId": "71",
    "city": "KOTA BITUNG",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7173",
    "provinceId": "71",
    "city": "KOTA TOMOHON",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7174",
    "provinceId": "71",
    "city": "KOTA KOTAMOBAGU",
    "province": "SULAWESI UTARA"
  },
  {
    "id": "7201",
    "provinceId": "72",
    "city": "KABUPATEN BANGGAI KEPULAUAN",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7202",
    "provinceId": "72",
    "city": "KABUPATEN BANGGAI",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7203",
    "provinceId": "72",
    "city": "KABUPATEN MOROWALI",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7204",
    "provinceId": "72",
    "city": "KABUPATEN POSO",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7205",
    "provinceId": "72",
    "city": "KABUPATEN DONGGALA",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7206",
    "provinceId": "72",
    "city": "KABUPATEN TOLI-TOLI",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7207",
    "provinceId": "72",
    "city": "KABUPATEN BUOL",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7208",
    "provinceId": "72",
    "city": "KABUPATEN PARIGI MOUTONG",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7209",
    "provinceId": "72",
    "city": "KABUPATEN TOJO UNA-UNA",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7210",
    "provinceId": "72",
    "city": "KABUPATEN SIGI",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7211",
    "provinceId": "72",
    "city": "KABUPATEN BANGGAI LAUT",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7212",
    "provinceId": "72",
    "city": "KABUPATEN MOROWALI UTARA",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7271",
    "provinceId": "72",
    "city": "KOTA PALU",
    "province": "SULAWESI TENGAH"
  },
  {
    "id": "7301",
    "provinceId": "73",
    "city": "KABUPATEN KEPULAUAN SELAYAR",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7302",
    "provinceId": "73",
    "city": "KABUPATEN BULUKUMBA",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7303",
    "provinceId": "73",
    "city": "KABUPATEN BANTAENG",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7304",
    "provinceId": "73",
    "city": "KABUPATEN JENEPONTO",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7305",
    "provinceId": "73",
    "city": "KABUPATEN TAKALAR",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7306",
    "provinceId": "73",
    "city": "KABUPATEN GOWA",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7307",
    "provinceId": "73",
    "city": "KABUPATEN SINJAI",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7308",
    "provinceId": "73",
    "city": "KABUPATEN MAROS",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7309",
    "provinceId": "73",
    "city": "KABUPATEN PANGKAJENE DAN KEPULAUAN",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7310",
    "provinceId": "73",
    "city": "KABUPATEN BARRU",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7311",
    "provinceId": "73",
    "city": "KABUPATEN BONE",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7312",
    "provinceId": "73",
    "city": "KABUPATEN SOPPENG",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7313",
    "provinceId": "73",
    "city": "KABUPATEN WAJO",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7314",
    "provinceId": "73",
    "city": "KABUPATEN SIDENRENG RAPPANG",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7315",
    "provinceId": "73",
    "city": "KABUPATEN PINRANG",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7316",
    "provinceId": "73",
    "city": "KABUPATEN ENREKANG",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7317",
    "provinceId": "73",
    "city": "KABUPATEN LUWU",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7318",
    "provinceId": "73",
    "city": "KABUPATEN TANA TORAJA",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7322",
    "provinceId": "73",
    "city": "KABUPATEN LUWU UTARA",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7325",
    "provinceId": "73",
    "city": "KABUPATEN LUWU TIMUR",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7326",
    "provinceId": "73",
    "city": "KABUPATEN TORAJA UTARA",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7371",
    "provinceId": "73",
    "city": "KOTA MAKASSAR",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7372",
    "provinceId": "73",
    "city": "KOTA PAREPARE",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7373",
    "provinceId": "73",
    "city": "KOTA PALOPO",
    "province": "SULAWESI SELATAN"
  },
  {
    "id": "7401",
    "provinceId": "74",
    "city": "KABUPATEN BUTON",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7402",
    "provinceId": "74",
    "city": "KABUPATEN MUNA",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7403",
    "provinceId": "74",
    "city": "KABUPATEN KONAWE",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7404",
    "provinceId": "74",
    "city": "KABUPATEN KOLAKA",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7405",
    "provinceId": "74",
    "city": "KABUPATEN KONAWE SELATAN",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7406",
    "provinceId": "74",
    "city": "KABUPATEN BOMBANA",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7407",
    "provinceId": "74",
    "city": "KABUPATEN WAKATOBI",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7408",
    "provinceId": "74",
    "city": "KABUPATEN KOLAKA UTARA",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7409",
    "provinceId": "74",
    "city": "KABUPATEN BUTON UTARA",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7410",
    "provinceId": "74",
    "city": "KABUPATEN KONAWE UTARA",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7411",
    "provinceId": "74",
    "city": "KABUPATEN KOLAKA TIMUR",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7412",
    "provinceId": "74",
    "city": "KABUPATEN KONAWE KEPULAUAN",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7413",
    "provinceId": "74",
    "city": "KABUPATEN MUNA BARAT",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7414",
    "provinceId": "74",
    "city": "KABUPATEN BUTON TENGAH",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7415",
    "provinceId": "74",
    "city": "KABUPATEN BUTON SELATAN",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7471",
    "provinceId": "74",
    "city": "KOTA KENDARI",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7472",
    "provinceId": "74",
    "city": "KOTA BAUBAU",
    "province": "SULAWESI TENGGARA"
  },
  {
    "id": "7501",
    "provinceId": "75",
    "city": "KABUPATEN BOALEMO",
    "province": "GORONTALO"
  },
  {
    "id": "7502",
    "provinceId": "75",
    "city": "KABUPATEN GORONTALO",
    "province": "GORONTALO"
  },
  {
    "id": "7503",
    "provinceId": "75",
    "city": "KABUPATEN POHUWATO",
    "province": "GORONTALO"
  },
  {
    "id": "7504",
    "provinceId": "75",
    "city": "KABUPATEN BONE BOLANGO",
    "province": "GORONTALO"
  },
  {
    "id": "7505",
    "provinceId": "75",
    "city": "KABUPATEN GORONTALO UTARA",
    "province": "GORONTALO"
  },
  {
    "id": "7571",
    "provinceId": "75",
    "city": "KOTA GORONTALO",
    "province": "GORONTALO"
  },
  {
    "id": "7601",
    "provinceId": "76",
    "city": "KABUPATEN MAJENE",
    "province": "SULAWESI BARAT"
  },
  {
    "id": "7602",
    "provinceId": "76",
    "city": "KABUPATEN POLEWALI MANDAR",
    "province": "SULAWESI BARAT"
  },
  {
    "id": "7603",
    "provinceId": "76",
    "city": "KABUPATEN MAMASA",
    "province": "SULAWESI BARAT"
  },
  {
    "id": "7604",
    "provinceId": "76",
    "city": "KABUPATEN MAMUJU",
    "province": "SULAWESI BARAT"
  },
  {
    "id": "7605",
    "provinceId": "76",
    "city": "KABUPATEN PASANGKAYU",
    "province": "SULAWESI BARAT"
  },
  {
    "id": "7606",
    "provinceId": "76",
    "city": "KABUPATEN MAMUJU TENGAH",
    "province": "SULAWESI BARAT"
  },
  {
    "id": "8101",
    "provinceId": "81",
    "city": "KABUPATEN KEPULAUAN TANIMBAR",
    "province": "MALUKU"
  },
  {
    "id": "8102",
    "provinceId": "81",
    "city": "KABUPATEN MALUKU TENGGARA",
    "province": "MALUKU"
  },
  {
    "id": "8103",
    "provinceId": "81",
    "city": "KABUPATEN MALUKU TENGAH",
    "province": "MALUKU"
  },
  {
    "id": "8104",
    "provinceId": "81",
    "city": "KABUPATEN BURU",
    "province": "MALUKU"
  },
  {
    "id": "8105",
    "provinceId": "81",
    "city": "KABUPATEN KEPULAUAN ARU",
    "province": "MALUKU"
  },
  {
    "id": "8106",
    "provinceId": "81",
    "city": "KABUPATEN SERAM BAGIAN BARAT",
    "province": "MALUKU"
  },
  {
    "id": "8107",
    "provinceId": "81",
    "city": "KABUPATEN SERAM BAGIAN TIMUR",
    "province": "MALUKU"
  },
  {
    "id": "8108",
    "provinceId": "81",
    "city": "KABUPATEN MALUKU BARAT DAYA",
    "province": "MALUKU"
  },
  {
    "id": "8109",
    "provinceId": "81",
    "city": "KABUPATEN BURU SELATAN",
    "province": "MALUKU"
  },
  {
    "id": "8171",
    "provinceId": "81",
    "city": "KOTA AMBON",
    "province": "MALUKU"
  },
  {
    "id": "8172",
    "provinceId": "81",
    "city": "KOTA TUAL",
    "province": "MALUKU"
  },
  {
    "id": "8201",
    "provinceId": "82",
    "city": "KABUPATEN HALMAHERA BARAT",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8202",
    "provinceId": "82",
    "city": "KABUPATEN HALMAHERA TENGAH",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8203",
    "provinceId": "82",
    "city": "KABUPATEN KEPULAUAN SULA",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8204",
    "provinceId": "82",
    "city": "KABUPATEN HALMAHERA SELATAN",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8205",
    "provinceId": "82",
    "city": "KABUPATEN HALMAHERA UTARA",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8206",
    "provinceId": "82",
    "city": "KABUPATEN HALMAHERA TIMUR",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8207",
    "provinceId": "82",
    "city": "KABUPATEN PULAU MOROTAI",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8208",
    "provinceId": "82",
    "city": "KABUPATEN PULAU TALIABU",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8271",
    "provinceId": "82",
    "city": "KOTA TERNATE",
    "province": "MALUKU UTARA"
  },
  {
    "id": "8272",
    "provinceId": "82",
    "city": "KOTA TIDORE KEPULAUAN",
    "province": "MALUKU UTARA"
  },
  {
    "id": "9101",
    "provinceId": "91",
    "city": "KABUPATEN FAKFAK",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9102",
    "provinceId": "91",
    "city": "KABUPATEN KAIMANA",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9103",
    "provinceId": "91",
    "city": "KABUPATEN TELUK WONDAMA",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9104",
    "provinceId": "91",
    "city": "KABUPATEN TELUK BINTUNI",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9105",
    "provinceId": "91",
    "city": "KABUPATEN MANOKWARI",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9111",
    "provinceId": "91",
    "city": "KABUPATEN MANOKWARI SELATAN",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9112",
    "provinceId": "91",
    "city": "KABUPATEN PEGUNUNGAN ARFAK",
    "province": "PAPUA BARAT"
  },
  {
    "id": "9201",
    "provinceId": "92",
    "city": "KABUPATEN RAJA AMPAT",
    "province": "PAPUA BARAT DAYA"
  },
  {
    "id": "9202",
    "provinceId": "92",
    "city": "KABUPATEN SORONG",
    "province": "PAPUA BARAT DAYA"
  },
  {
    "id": "9203",
    "provinceId": "92",
    "city": "KABUPATEN SORONG SELATAN",
    "province": "PAPUA BARAT DAYA"
  },
  {
    "id": "9204",
    "provinceId": "92",
    "city": "KABUPATEN MAYBRAT",
    "province": "PAPUA BARAT DAYA"
  },
  {
    "id": "9205",
    "provinceId": "92",
    "city": "KABUPATEN TAMBRAUW",
    "province": "PAPUA BARAT DAYA"
  },
  {
    "id": "9271",
    "provinceId": "92",
    "city": "KOTA SORONG",
    "province": "PAPUA BARAT DAYA"
  },
  {
    "id": "9403",
    "provinceId": "94",
    "city": "KABUPATEN JAYAPURA",
    "province": "PAPUA"
  },
  {
    "id": "9408",
    "provinceId": "94",
    "city": "KABUPATEN KEPULAUAN YAPEN",
    "province": "PAPUA"
  },
  {
    "id": "9409",
    "provinceId": "94",
    "city": "KABUPATEN BIAK NUMFOR",
    "province": "PAPUA"
  },
  {
    "id": "9419",
    "provinceId": "94",
    "city": "KABUPATEN SARMI",
    "province": "PAPUA"
  },
  {
    "id": "9420",
    "provinceId": "94",
    "city": "KABUPATEN KEEROM",
    "province": "PAPUA"
  },
  {
    "id": "9426",
    "provinceId": "94",
    "city": "KABUPATEN WAROPEN",
    "province": "PAPUA"
  },
  {
    "id": "9427",
    "provinceId": "94",
    "city": "KABUPATEN SUPIORI",
    "province": "PAPUA"
  },
  {
    "id": "9428",
    "provinceId": "94",
    "city": "KABUPATEN MAMBERAMO RAYA",
    "province": "PAPUA"
  },
  {
    "id": "9471",
    "provinceId": "94",
    "city": "KOTA JAYAPURA",
    "province": "PAPUA"
  },
  {
    "id": "9501",
    "provinceId": "95",
    "city": "KABUPATEN MERAUKE",
    "province": "PAPUA SELATAN"
  },
  {
    "id": "9502",
    "provinceId": "95",
    "city": "KABUPATEN BOVEN DIGOEL",
    "province": "PAPUA SELATAN"
  },
  {
    "id": "9503",
    "provinceId": "95",
    "city": "KABUPATEN MAPPI",
    "province": "PAPUA SELATAN"
  },
  {
    "id": "9504",
    "provinceId": "95",
    "city": "KABUPATEN ASMAT",
    "province": "PAPUA SELATAN"
  },
  {
    "id": "9601",
    "provinceId": "96",
    "city": "KABUPATEN MIMIKA",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9602",
    "provinceId": "96",
    "city": "KABUPATEN DOGIYAI",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9603",
    "provinceId": "96",
    "city": "KABUPATEN DEIYAI",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9604",
    "provinceId": "96",
    "city": "KABUPATEN NABIRE",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9605",
    "provinceId": "96",
    "city": "KABUPATEN PANIAI",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9606",
    "provinceId": "96",
    "city": "KABUPATEN INTAN JAYA",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9607",
    "provinceId": "96",
    "city": "KABUPATEN PUNCAK",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9608",
    "provinceId": "96",
    "city": "KABUPATEN PUNCAK JAYA",
    "province": "PAPUA TENGAH"
  },
  {
    "id": "9701",
    "provinceId": "97",
    "city": "KABUPATEN NDUGA",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9702",
    "provinceId": "97",
    "city": "KABUPATEN JAYAWIJAYA",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9703",
    "provinceId": "97",
    "city": "KABUPATEN LANNY JAYA",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9704",
    "provinceId": "97",
    "city": "KABUPATEN TOLIKARA",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9705",
    "provinceId": "97",
    "city": "KABUPATEN MAMBERAMO TENGAH",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9706",
    "provinceId": "97",
    "city": "KABUPATEN YALIMO",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9707",
    "provinceId": "97",
    "city": "KABUPATEN YAHUKIMO",
    "province": "PAPUA PEGUNUNGAN"
  },
  {
    "id": "9708",
    "provinceId": "97",
    "city": "KABUPATEN PEGUNUNGAN BINTANG",
    "province": "PAPUA PEGUNUNGAN"
  }
];
const regionIndex = new Map(INDONESIA_REGENCIES.map((region) => [region.id, region]));
export function findIndonesianRegency(code: string): Regency | undefined {
  return regionIndex.get(code);
}
