import { UstadzProfile } from "@/lib/ustadzApi";

export const ustadzPreviewProfiles: UstadzProfile[] = [
  {
    id: "preview-ustadz-1",
    fullName: "Muhammad Abdullah",
    normalizedName: "muhammad abdullah",
    titlePrefix: "Dr.",
    titleSuffix: "Lc., M.A.",
    email: "m.abdullah@example.id",
    phone: "6281233334444",
    whatsapp: "6281233334444",
    cityCode: "3273",
    provinceCode: "32",
    address: "Bandung, Jawa Barat",
    educationSummary: "Pendidikan tinggi bidang syariah dan studi Islam.",
    expertiseSummary: "Fikih ibadah, muamalah, dan pendidikan keluarga.",
    profileStatus: "ACTIVE",
    primaryInstitution: {
      institutionId: "preview-institution-1",
      institutionName: "Ma'had Ilmu Bandung",
      institutionCode: "MIB-01",
      position: "Pembina",
      isPrimary: true,
      status: "ACTIVE",
    },
    affiliationCount: 2,
    hasDuplicateAlert: true,
    completenessPercent: 92,
    affiliations: [
      {
        id: "preview-affiliation-1",
        institutionId: "preview-institution-1",
        institutionName: "Ma'had Ilmu Bandung",
        institutionCode: "MIB-01",
        position: "Pembina",
        isPrimary: true,
        startDate: "2020-01-01",
        status: "ACTIVE",
      },
      {
        id: "preview-affiliation-2",
        institutionId: "preview-institution-2",
        institutionName: "Yayasan Dakwah Cimahi",
        institutionCode: "YDC-02",
        position: "Penasihat",
        isPrimary: false,
        startDate: "2022-06-15",
        status: "ACTIVE",
      },
    ],
    eventHistory: [
      {
        participantId: "preview-participant-1",
        participantCode: "AST-2026-001",
        confirmationStatus: "CONFIRMED",
        approvalStatus: "APPROVED",
        eventId: "preview-event-1",
        eventCode: "DAU-2026-01",
        eventName: "Daurah Asatidz Nasional",
        eventStatus: "PUBLISHED",
        eventStartDate: "2026-08-15",
        eventEndDate: "2026-08-17",
        attendanceCount: 3,
      },
    ],
  },
  {
    id: "preview-ustadz-2",
    fullName: "Abu Ahmad Zakaria",
    normalizedName: "abu ahmad zakaria",
    email: "abu.ahmad@example.id",
    phone: "6281955556666",
    profileStatus: "ACTIVE",
    primaryInstitution: {
      institutionId: "preview-institution-3",
      institutionName: "Pesantren Al-Hikmah",
      institutionCode: "PAH-03",
      position: "Pengajar",
      isPrimary: true,
      status: "ACTIVE",
    },
    affiliationCount: 1,
    hasDuplicateAlert: false,
    completenessPercent: 68,
  },
  {
    id: "preview-ustadz-3",
    fullName: "Muhammad Abdullah",
    normalizedName: "muhammad abdullah",
    titleSuffix: "Lc.",
    phone: "6281233334444",
    cityCode: "3273",
    provinceCode: "32",
    profileStatus: "INACTIVE",
    primaryInstitution: null,
    affiliationCount: 0,
    hasDuplicateAlert: true,
    completenessPercent: 43,
  },
];

export const getUstadzPreviewProfile = (id?: string) =>
  ustadzPreviewProfiles.find((profile) => profile.id === id) || ustadzPreviewProfiles[0];
