import React, { useEffect, useState } from "react";
import { CalendarClock, CheckCircle2, KeyRound, MapPin, ShieldCheck } from "lucide-react";
import { CommitteeLayout } from "@/components/layouts/CommitteeLayout";
import { PageHeader } from "@/components/common/PageHeader";
import { StatusBadge } from "@/components/common/StatusBadge";
import { committeeApi, CommitteeAssignment, formatCommitteeDate, roleLabel } from "@/lib/committeeApi";

export const CommitteeAssignmentsPage: React.FC = () => {
  const [assignments, setAssignments] = useState<CommitteeAssignment[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { void committeeApi<{ assignments: CommitteeAssignment[] }>("/committee/context").then((data) => setAssignments(data.assignments)).catch((err) => setError(err instanceof Error ? err.message : "Tugas gagal dimuat.")); }, []);
  const now = new Date();
  return <CommitteeLayout><PageHeader title="Tugas & Akses Saya" description="Lihat event yang ditugaskan, masa berlaku akses, dan tenggat yang perlu diawasi." breadcrumbs={[{ label: "Panitia", href: "/committee" }, { label: "Tugas saya" }]} />{error && <div role="alert" className="mb-5 border-t-4 border-rose-600 bg-rose-50 p-4 text-sm text-rose-900">{error}</div>}<div className="space-y-4">{assignments.map((assignment) => {
    const ended = Boolean(assignment.endsAt && new Date(assignment.endsAt) < now);
    const upcoming = Boolean(assignment.startsAt && new Date(assignment.startsAt) > now);
    return <article key={assignment.id} className="border-t-4 border-teal-800 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.14em] text-teal-800">{assignment.eventCode}</p><h2 className="mt-1 text-xl font-black text-slate-950">{assignment.eventName}</h2><p className="mt-2 text-sm font-bold text-slate-700">{roleLabel(assignment.committeeRole)}</p></div><StatusBadge label={ended ? "Tugas berakhir" : upcoming ? "Belum dimulai" : "Tugas aktif"} variant={ended ? "danger" : upcoming ? "warning" : "success"} /></div><div className="mt-5 grid gap-4 border-y border-slate-200 py-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs font-bold text-slate-500">Masa tugas</p><p className="mt-1 text-sm font-black">{formatCommitteeDate(assignment.startsAt)}<br />s.d. {formatCommitteeDate(assignment.endsAt)}</p></div><div><p className="text-xs font-bold text-slate-500">Lokasi</p><p className="mt-1 text-sm font-black"><MapPin className="mr-1 inline h-4 w-4 text-teal-700" />{assignment.venueName || "Belum ditetapkan"}</p></div><div><p className="text-xs font-bold text-slate-500">Respons undangan</p><p className="mt-1 text-sm font-black"><CalendarClock className="mr-1 inline h-4 w-4 text-teal-700" />{formatCommitteeDate(assignment.invitationResponseDeadline)}</p></div><div><p className="text-xs font-bold text-slate-500">Konfirmasi hadir</p><p className="mt-1 text-sm font-black"><CheckCircle2 className="mr-1 inline h-4 w-4 text-teal-700" />{formatCommitteeDate(assignment.attendanceConfirmationDeadline)}</p></div></div><div className="mt-4"><p className="mb-2 text-xs font-black uppercase tracking-wide text-slate-500"><KeyRound className="mr-1 inline h-4 w-4" />Akses efektif</p><div className="flex flex-wrap gap-2">{assignment.effectivePermissions?.map((permission) => <span key={permission} className="border border-slate-200 bg-slate-50 px-2 py-1 text-xs font-bold text-slate-700">{permission}</span>)}</div></div></article>;
  })}{!error && assignments.length === 0 && <div className="border border-dashed border-slate-300 bg-white p-10 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-slate-400" /><p className="mt-3 text-sm font-bold text-slate-700">Belum ada penugasan event aktif.</p><p className="mt-1 text-xs text-slate-500">Hubungi admin untuk menetapkan event dan peran.</p></div>}</div></CommitteeLayout>;
};
